In [1]:
import pandas as pd
import requests
import math

## 1. all of the data for people
Using the code from the lesson as a guide and the REST API from https://swapi.dev/ as we did in the lesson, create a dataframe named people that has all of the data for people.

In [2]:
url = 'https://swapi.dev/api/people/5'
response = requests.get(url)
print(response.text)

{"name":"Leia Organa","height":"150","mass":"49","hair_color":"brown","skin_color":"light","eye_color":"brown","birth_year":"19BBY","gender":"female","homeworld":"https://swapi.dev/api/planets/2/","films":["https://swapi.dev/api/films/1/","https://swapi.dev/api/films/2/","https://swapi.dev/api/films/3/","https://swapi.dev/api/films/6/"],"species":[],"vehicles":["https://swapi.dev/api/vehicles/30/"],"starships":[],"created":"2014-12-10T15:20:09.791000Z","edited":"2014-12-20T21:17:50.315000Z","url":"https://swapi.dev/api/people/5/"}

In [3]:
response = requests.get('https://swapi.dev/api/people/')

data = response.json()
data.keys()

dict_keys(['count', 'next', 'previous', 'results'])

In [4]:
number_of_people = data['count']
next_page = data['next']
previous_page = data['previous']

print(f'number_of_people: {number_of_people}')
print(f'next_page: {next_page}')
print(f'previous_page: {previous_page}')

number_of_people: 82
next_page: https://swapi.dev/api/people/?page=2
previous_page: None

In [5]:
data['results'][:2]

[{'name': 'Luke Skywalker',
  'height': '172',
  'mass': '77',
  'hair_color': 'blond',
  'skin_color': 'fair',
  'eye_color': 'blue',
  'birth_year': '19BBY',
  'gender': 'male',
  'homeworld': 'https://swapi.dev/api/planets/1/',
  'films': ['https://swapi.dev/api/films/1/',
   'https://swapi.dev/api/films/2/',
   'https://swapi.dev/api/films/3/',
   'https://swapi.dev/api/films/6/'],
  'species': [],
  'vehicles': ['https://swapi.dev/api/vehicles/14/',
   'https://swapi.dev/api/vehicles/30/'],
  'starships': ['https://swapi.dev/api/starships/12/',
   'https://swapi.dev/api/starships/22/'],
  'created': '2014-12-09T13:50:51.644000Z',
  'edited': '2014-12-20T21:17:56.891000Z',
  'url': 'https://swapi.dev/api/people/1/'},
 {'name': 'C-3PO',
  'height': '167',
  'mass': '75',
  'hair_color': 'n/a',
  'skin_color': 'gold',
  'eye_color': 'yellow',
  'birth_year': '112BBY',
  'gender': 'n/a',
  'homeworld': 'https://swapi.dev/api/planets/1/',
  'films': ['https://swapi.dev/api/films/1/',
   'https://swapi.dev/api/films/2/',
   'https://swapi.dev/api/films/3/',
   'https://swapi.dev/api/films/4/',
   'https://swapi.dev/api/films/5/',
   'https://swapi.dev/api/films/6/'],
  'species': ['https://swapi.dev/api/species/2/'],
  'vehicles': [],
  'starships': [],
  'created': '2014-12-10T15:10:51.357000Z',
  'edited': '2014-12-20T21:17:50.309000Z',
  'url': 'https://swapi.dev/api/people/2/'}]

In [6]:
#calculate the number of pages
number_of_results = len(data['results'])
max_page = math.ceil(number_of_people / number_of_results)

print(f'number_of_results: {number_of_results}')
print(f'max_page: {max_page}')

number_of_results: 10
max_page: 9

In [7]:
# make it a dataframe
df = pd.DataFrame(data['results'])
df.head()

,name,height,mass,hair_color,skin_color,eye_color,birth_year,gender,homeworld,films,species,vehicles,starships,created,edited,url
0,Luke Skywalker,172,77,blond,fair,blue,19BBY,male,https://swapi.dev/api/planets/1/,"[https://swapi.dev/api/films/1/, https://swapi...",[],"[https://swapi.dev/api/vehicles/14/, https://s...","[https://swapi.dev/api/starships/12/, https://...",2014-12-09T13:50:51.644000Z,2014-12-20T21:17:56.891000Z,https://swapi.dev/api/people/1/
1,C-3PO,167,75,n/a,gold,yellow,112BBY,n/a,https://swapi.dev/api/planets/1/,"[https://swapi.dev/api/films/1/, https://swapi...",[https://swapi.dev/api/species/2/],[],[],2014-12-10T15:10:51.357000Z,2014-12-20T21:17:50.309000Z,https://swapi.dev/api/people/2/
2,R2-D2,96,32,n/a,"white, blue",red,33BBY,n/a,https://swapi.dev/api/planets/8/,"[https://swapi.dev/api/films/1/, https://swapi...",[https://swapi.dev/api/species/2/],[],[],2014-12-10T15:11:50.376000Z,2014-12-20T21:17:50.311000Z,https://swapi.dev/api/people/3/
3,Darth Vader,202,136,none,white,yellow,41.9BBY,male,https://swapi.dev/api/planets/1/,"[https://swapi.dev/api/films/1/, https://swapi...",[],[],[https://swapi.dev/api/starships/13/],2014-12-10T15:18:20.704000Z,2014-12-20T21:17:50.313000Z,https://swapi.dev/api/people/4/
4,Leia Organa,150,49,brown,light,brown,19BBY,female,https://swapi.dev/api/planets/2/,"[https://swapi.dev/api/films/1/, https://swapi...",[],[https://swapi.dev/api/vehicles/30/],[],2014-12-10T15:20:09.791000Z,2014-12-20T21:17:50.315000Z,https://swapi.dev/api/people/5/

In [8]:
df.shape

(10, 16)

In [9]:
# get data from the next page and add to df
response = requests.get(data['next'])
data = response.json()

number_of_people = data['count']
next_page = data['next']
previous_page = data['previous']
number_of_results = len(data['results'])
max_page = math.ceil(number_of_people / number_of_results)

print(f'number_of_people: {number_of_people}')
print(f'next_page: {next_page}')
print(f'previous_page: {previous_page}')
print(f'number_of_results: {number_of_results}')
print(f'max_page: {max_page}')

df = pd.concat([df, pd.DataFrame(data['results'])]).reset_index()

number_of_people: 82
next_page: https://swapi.dev/api/people/?page=3
previous_page: https://swapi.dev/api/people/?page=1
number_of_results: 10
max_page: 9

In [10]:
# do it again
response = requests.get(data['next'])
data = response.json()

number_of_people = data['count']
next_page = data['next']
previous_page = data['previous']
number_of_results = len(data['results'])
max_page = math.ceil(number_of_people / number_of_results)

print(f'number_of_people: {number_of_people}')
print(f'next_page: {next_page}')
print(f'previous_page: {previous_page}')
print(f'number_of_results: {number_of_results}')
print(f'max_page: {max_page}')

df = pd.concat([df, pd.DataFrame(data['results'])]).reset_index()

number_of_people: 82
next_page: https://swapi.dev/api/people/?page=4
previous_page: https://swapi.dev/api/people/?page=2
number_of_results: 10
max_page: 9

In [11]:
df.shape

(30, 18)

In [16]:
df.shape

(30, 18)

In [ ]:
# all in one place

url = 'https://swapi.dev/api/people/5'
response = requests.get(url)
print(response.text)
# make a dataframe
df = pd.DataFrame(data['results'])
response = requests.get('https://swapi.dev/api/people/')

data = response.json()
data.keys()

response = requests.get(data['next'])
data = response.json()

number_of_people = data['count']
next_page = data['next']
previous_page = data['previous']
number_of_results = len(data['results'])
max_page = math.ceil(number_of_people / number_of_results)

print(f'number_of_people: {number_of_people}')
print(f'next_page: {next_page}')
print(f'previous_page: {previous_page}')
print(f'number_of_results: {number_of_results}')
print(f'max_page: {max_page}')

df = pd.concat([df, pd.DataFrame(data['results'])]).reset_index()
#calculate the number of pages
number_of_results = len(data['results'])
max_page = math.ceil(number_of_people / number_of_results)

print(f'number_of_results: {number_of_results}')
print(f'max_page: {max_page}')

In [45]:
#make a function to get data

def fetch_all_people():
    ''' 
    pulls in people data from swapi.dev and makes a df
    to run:
    people_data = fetch_all_people()
    people = pd.DataFrame(people_data)
    '''
    #set url
    url = "https://swapi.dev/api/people/"
    #make list
    people = []
    #make loop
    while url is not None:
        response = requests.get(url)
        data = response.json()
        people.extend(data["results"])
        url = data["next"]
    
    return people

In [46]:
people_data = fetch_all_people()
people = pd.DataFrame(people_data)

In [47]:
people.shape

(82, 16)

## 2.Do the same thing, but for planets.

In [48]:
def fetch_all_planets():
    ''' 
    pulls in planets data from swapi.dev and makes a df
    to run:
    planets_data = fetch_all_planets()
    planets = pd.DataFrame(planets_data)
    '''
    url = "https://swapi.dev/api/planets/"
    planets = []
    
    while url is not None:
        response = requests.get(url)
        data = response.json()
        planets.extend(data["results"])
        url = data["next"]
    
    return planets

In [49]:
planets_data = fetch_all_planets()
planets = pd.DataFrame(planets_data)

In [50]:
planets.shape

(60, 14)

## 3. Extract the data for starships.

In [51]:
def fetch_all_starships():
    ''' 
    pulls in starships data from swapi.dev and makes a df
    to run:
    starships_data = fetch_all_starships()
    starships = pd.DataFrame(starships_data)
    '''
    url = "https://swapi.dev/api/starships/"
    starships = []
    while url is not None:
        response = requests.get(url)
        data = response.json()
        starships.extend(data["results"])
        url = data["next"]
    return starships

In [52]:
starships_data = fetch_all_starships()
starships = pd.DataFrame(starships_data)

In [53]:
starships.shape

(36, 18)

## 4. Save the data in your files to local csv files so that it will be faster to access in the future.

In [33]:
# make  .csv files
people.to_csv('people.csv', index=False)
planets.to_csv('planets.csv', index=False)
starships.to_csv('starships.csv', index=False)

## 5. Combine the data from your three separate dataframes into one large dataframe.

In [54]:
# Read the individual CSV files
people = pd.read_csv('people.csv')
planets = pd.read_csv('planets.csv')
starships = pd.read_csv('starships.csv')

# Concatenate the DataFrames
starwars = pd.concat([people, planets, starships], axis=0)

# Save the combined DataFrame to a new CSV file
starwars.to_csv('starwars.csv', index=False)

In [55]:
starwars = pd.read_csv('starwars.csv')

In [56]:
starwars.shape

(178, 38)

In [38]:
starwars.sample(10)

,name,height,mass,hair_color,skin_color,eye_color,birth_year,gender,homeworld,films,...,cargo_capacity,consumables,hyperdrive_rating,MGLT,starship_class,pilots,films.2,created.2,edited.2,url.2
13,Han Solo,180,80,brown,fair,brown,29BBY,male,https://swapi.dev/api/planets/22/,"['https://swapi.dev/api/films/1/', 'https://sw...",...,unknown,2 years,1.0,60,Star Cruiser,[],['https://swapi.dev/api/films/3/'],2014-12-18T10:54:57.804000Z,2014-12-20T21:23:49.904000Z,https://swapi.dev/api/starships/27/
4,Leia Organa,150,49,brown,light,brown,19BBY,female,https://swapi.dev/api/planets/2/,"['https://swapi.dev/api/films/1/', 'https://sw...",...,100000,2 months,0.5,75,Light freighter,"['https://swapi.dev/api/people/13/', 'https://...","['https://swapi.dev/api/films/1/', 'https://sw...",2014-12-10T16:59:45.094000Z,2014-12-20T21:23:49.880000Z,https://swapi.dev/api/starships/10/
39,Sebulba,112,40,none,"grey, red",orange,unknown,male,https://swapi.dev/api/planets/35/,['https://swapi.dev/api/films/4/'],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,R5-D4,97,32,NaN,"white, red",red,unknown,NaN,https://swapi.dev/api/planets/1/,['https://swapi.dev/api/films/1/'],...,150,5 days,1.0,105,Starfighter,['https://swapi.dev/api/people/4/'],['https://swapi.dev/api/films/1/'],2014-12-12T11:21:32.991000Z,2014-12-20T21:23:49.889000Z,https://swapi.dev/api/starships/13/
50,Ki-Adi-Mundi,198,82,white,pale,yellow,92BBY,male,https://swapi.dev/api/planets/43/,"['https://swapi.dev/api/films/4/', 'https://sw...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Greedo,173,74,NaN,green,black,44BBY,male,https://swapi.dev/api/planets/23/,['https://swapi.dev/api/films/1/'],...,40,1 week,1.0,120,Starfighter,['https://swapi.dev/api/people/29/'],['https://swapi.dev/api/films/3/'],2014-12-18T11:16:34.542000Z,2014-12-20T21:23:49.907000Z,https://swapi.dev/api/starships/28/
34,Jar Jar Binks,196,66,none,orange,orange,52BBY,male,https://swapi.dev/api/planets/8/,"['https://swapi.dev/api/films/4/', 'https://sw...",...,140,7 days,6,unknown,starfighter,"['https://swapi.dev/api/people/10/', 'https://...",['https://swapi.dev/api/films/6/'],2014-12-20T20:38:05.031000Z,2014-12-20T21:23:49.959000Z,https://swapi.dev/api/starships/74/
49,Mace Windu,188,84,none,dark,brown,72BBY,male,https://swapi.dev/api/planets/42/,"['https://swapi.dev/api/films/4/', 'https://sw...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,Darth Maul,175,80,none,red,yellow,54BBY,male,https://swapi.dev/api/planets/36/,['https://swapi.dev/api/films/4/'],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56,Plo Koon,188,80,none,orange,black,22BBY,male,https://swapi.dev/api/planets/49/,"['https://swapi.dev/api/films/4/', 'https://sw...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## 6. Acquire the Open Power Systems Data for Germany,
which has been rapidly expanding its renewable energy production in recent years. The data set includes country-wide totals of electricity consumption, wind power production, and solar power production for 2006-2017. You can get the data here: https://raw.githubusercontent.com/jenfly/opsd/master/opsd_germany_daily.csv

In [42]:
# make function
def acquire_opsd_data():
    '''
    This function acquires the Open Power Systems Data for Germany (opsd) from
     "https://raw.githubusercontent.com/jenfly/opsd/master/opsd_germany_daily.csv"
     it returns an error message if failed
     # Usage ex:  opsd_data = acquire_opsd_data()
    '''
    url = "https://raw.githubusercontent.com/jenfly/opsd/master/opsd_germany_daily.csv"
    
    try:
        data = pd.read_csv(url)
        return data
    except Exception as e:
        print(f"Error occurred while acquiring data: {str(e)}")
        return None

In [43]:
opsd_data = acquire_opsd_data()

In [44]:
opsd_data.sample(10)

            Date  Consumption     Wind    Solar  Wind+Solar
969   2008-08-27   1378.07900      NaN      NaN         NaN
4216  2017-07-18   1380.63900   79.389  216.313     295.702
1201  2009-04-16   1251.39100      NaN      NaN         NaN
2034  2011-07-28   1305.67300   40.956      NaN         NaN
4271  2017-09-11   1411.22858  576.260  102.462     678.722
1499  2010-02-08   1516.01200   32.000      NaN         NaN
141   2006-05-22   1358.08200      NaN      NaN         NaN
4279  2017-09-19   1429.80947   86.278   93.989     180.267
2593  2013-02-06   1451.44900  100.776   31.005     131.781
2258  2012-03-08   1412.18100  150.182   44.725     194.907

## 7. Make sure all the work that you have done above is reproducible.
That is, you should put the code above into separate functions in the acquire.py file and be able to re-run the functions and get the same data.

This was done during previous steps